# General Site Settings
baseurl: ""  # Leave this blank since you are using a custom domain
url: "https://theoremsandthings.com"  # Your custom domain, including the protocol (https://)
image: '/images/scientistskele.png'
title: "Theorems and Things"

#-------------------------------
# Build settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 8
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed